### ISSUE TITLE
NEDEN ÇALIYON AÇIK KAYNAK KODUNU

### ISSUE THREAD

**Issue by dermany0** [Bora185/SMS-Bomber#1]
ENOUGH TİNGİRİFİSTİK BUNUN SAHİBİ BENDE ÇALDIM KENDİMİN GİBİ GÖSTERDİM EHEHE PUAGAGA İKİMİZDE GÖTÜZ GALİBA AMA SONSUZ OLMASI İYİ OLMUŞ PUAHGGAGA :D

**Comment by Bora185** [comment]
Dostum tingirifistik'in yaptığı Enough projesi MIT lisanslı. Bu da "kullanıcıların projeyi ücretsiz olarak kullanmalarına, değiştirmelerine veya dağıtmalarına izin verirken, aynı zamanda projeyi satamazlar veya kapalı kaynak lisansları altında kullanamazlar." anlamına geliyor. Dikkat edersen "değiştirmelerine ve dağıtmalarına izin verir" yazıyor. Bilip bilmeden yorum yapma. Ayrıca açıklama ve "readme.md" dosyasına "Enough SMS Bomber by @tingirifistik. Modded By @Bora185" şeklinde yazdım. Projenin sahibinin tingirifistik olduğunu ve benim tarafımdan değiştirilip yayınlandığını belirttim.
